# Generated by Django 3.0.8 on 2020-07-11 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(64)])),
                ('authority', models.SmallIntegerField(choices=[(99, 'admin'), (1, 'general')], default=1)),
                ('updated_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('created_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gate.User')),
            ],
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['logged_time'], name='idx_user_log_logged_time'),
        ),
    ]
