# Generated by Django 3.0.8 on 2021-01-28 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=512, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(512)])),
                ('authority', models.SmallIntegerField(choices=[(99, 'admin'), (1, 'general')], default=1)),
                ('updated_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('created_time', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user information table',
                'verbose_name_plural': 'user information table',
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, null=True)),
                ('logged_time', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='gate.User')),
            ],
            options={
                'verbose_name': 'user log information',
                'verbose_name_plural': 'user log information',
            },
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['logged_time'], name='idx_user_log_logged_time'),
        ),
    ]
