# Generated by Django 3.0.8 on 2021-02-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-authority'], 'verbose_name': 'user information table', 'verbose_name_plural': 'user information table'},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-logged_time'], 'verbose_name': 'user log information', 'verbose_name_plural': 'user log information'},
        ),
    ]
