# Generated by Django 3.0.8 on 2020-07-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_auto_20200712_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gate.User'),
        ),
    ]
