# Generated by Django 3.0.8 on 2020-07-18 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0004_auto_20200718_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=512, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(512)]),
        ),
    ]
