# Generated by Django 3.0.8 on 2020-11-02 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0005_auto_20200718_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user information table', 'verbose_name_plural': 'user information table'},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'verbose_name': 'user log information', 'verbose_name_plural': 'user log information'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userlog',
            table='user_log',
        ),
    ]
