# Generated by Django 3.0.8 on 2020-11-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0006_auto_20201102_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='token',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
