# Generated by Django 3.0.8 on 2020-11-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0007_userlog_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userlog',
            table=None,
        ),
    ]
