# Generated by Django 3.0.8 on 2021-01-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0008_auto_20201102_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
