# Generated by Django 3.0.8 on 2021-03-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gate', '0002_auto_20210217_2152'),
        ('schedule', '0002_auto_20210309_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='gate.User'),
        ),
    ]
