# Generated by Django 3.0.8 on 2021-01-28 13:25

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VechainCandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('period', unixtimestampfield.fields.UnixTimeStampField(default=0.0)),
            ],
            options={
                'verbose_name': 'CoinCap VeChain candle data table',
                'verbose_name_plural': 'CoinCap VeChain candle data table',
            },
        ),
        migrations.AddIndex(
            model_name='vechaincandle',
            index=models.Index(fields=['period'], name='idx_vechain_candle_period'),
        ),
    ]
