# Generated by Django 3.0.8 on 2021-02-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vechaincandle',
            options={'ordering': ['-period'], 'verbose_name': 'CoinCap VeChain candle data table', 'verbose_name_plural': 'CoinCap VeChain candle data table'},
        ),
    ]
